### ISSUE TITLE
Test private repo with apikey gives NameError

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#302]
In #286 support for authenticated requests to the source code platform are added. However setting the apikey and running howfairis on a private repo now gives unexpected error:

```
Traceback (most recent call last):
  File "/home/verhoes/git/fair-software/howfairis/venv3/bin/howfairis", line 11, in <module>
    load_entry_point('howfairis', 'console_scripts', 'howfairis')()
  File "/home/verhoes/git/fair-software/howfairis/venv3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/verhoes/git/fair-software/howfairis/venv3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/verhoes/git/fair-software/howfairis/venv3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/verhoes/git/fair-software/howfairis/venv3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/verhoes/git/fair-software/howfairis/howfairis/cli/cli.py", line 66, in cli
    repo = Repo(url, branch, path)
  File "/home/verhoes/git/fair-software/howfairis/howfairis/repo.py", line 42, in __init__
    self._apikeys = get_apikeys_from_env_vars()
  File "/home/verhoes/git/fair-software/howfairis/howfairis/get_apikeys_from_env_vars.py", line 8, in get_apikeys_from_env_vars
    if apikey_github is None:
NameError: name 'apikey_github' is not defined

```

**Comment by sverhoeven** [comment]
Nevermind random clipboard paste corrupted code.
